//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class EDI
{

    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BODY", typeof(EDIBODY), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("HEADER", typeof(EDIHEADER), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class EDIBODY
{

    private EDIBODYORDERS[] oRDERSField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ORDERS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EDIBODYORDERS[] ORDERS
    {
        get
        {
            return this.oRDERSField;
        }
        set
        {
            this.oRDERSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class EDIBODYORDERS
{

    private string docFunktionField;

    private string firmaNrField;

    private string orderNrField;

    private string kundenOrderNrField;

    private string orderDatumField;

    private string auftragsDatumField;

    private string saisonField;

    private string auftragstypField;

    private string auftragsartField;

    private string terminartField;

    private string lieferDatumAnfangField;

    private string lieferDatumEndeField;

    private string nichtLiefernVorField;

    private string iLNBestellerField;

    private string bestName1Field;

    private string bestName2Field;

    private string bestName3Field;

    private string bestStrasseField;

    private string bestLandField;

    private string bestOrtField;

    private string bestPlzField;

    private string besteMailField;

    private string bestTelefonField;

    private string bestFaxField;

    private string iLNLiAnschriftField;

    private string liefAdressIdField;

    private string liefName1Field;

    private string liefName2Field;

    private string liefName3Field;

    private string liefStrasseField;

    private string liefLandField;

    private string liefOrtField;

    private string liefPlzField;

    private string liefeMailField;

    private string liefTelefonField;

    private string liefFaxField;

    private string iLNReAnschriftField;

    private string rechName1Field;

    private string rechName2Field;

    private string rechName3Field;

    private string rechStrasseField;

    private string rechLandField;

    private string rechOrtField;

    private string rechPlzField;

    private string recheMailField;

    private string rechTelefonField;

    private string rechFaxField;

    private string bestellartField;

    private string versandartField;

    private string zahlungsBedField;

    private string lieferBedField;

    private string waehrungField;

    private string bemerkungField;

    private string mwStStatusField;

    private string mwSt1SatzField;

    private string mwSt2SatzField;

    private string bruttoRechnungField;

    private string preislisteNrField;

    private string preislisteProgrammField;

    private string swiftField;

    private string iBANField;

    private string sEPAMandattypField;

    private string sEPAMandatnrField;

    private string spracheField;

    private string teillieferungField;

    private string valutadatumField;

    private string versandkostenField;

    private string versandkostenGebuehrField;

    private string versandkostenTextField;

    private string versandkostenMwstField;

    private string zANummerField;

    private string zABezeichnungField;

    private string zAReferenzField;

    private string zAAbschlagField;

    private string zATypField;

    private string zAPreisField;

    private string zABanknameField;

    private string zABLZField;

    private string zAKontonrField;

    private string zAKontoinhaberField;

    private string zABezahltAmField;

    private string bestellerField;

    private string ustIDField;

    private string skonto1TageField;

    private string skonto1ProzField;

    private string skonto2TageField;

    private string skonto2ProzField;

    private string nettoTageField;

    private string vertreterNrField;

    private string lagerortField;

    private string lagerOrtNachField;

    private string shopnummerField;

    private string kopfRabatt1Field;

    private string kopfRabatt1IdField;

    private string kopfRabatt2Field;

    private string kopfRabatt2IdField;

    private string kollektionField;

    private string produktbereichField;

    private string diverseKundenNrField;

    private string orderIDFremdsystemField;

    private string suchmerkmalField;

    private string rechnungstypField;

    private string freitext1Field;

    private string zAText1Field;

    private string bemerkungInternField;

    private string streckenlieferungField;

    private EDIBODYORDERSORDPOS[] oRDPOSField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocFunktion
    {
        get
        {
            return this.docFunktionField;
        }
        set
        {
            this.docFunktionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FirmaNr
    {
        get
        {
            return this.firmaNrField;
        }
        set
        {
            this.firmaNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrderNr
    {
        get
        {
            return this.orderNrField;
        }
        set
        {
            this.orderNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KundenOrderNr
    {
        get
        {
            return this.kundenOrderNrField;
        }
        set
        {
            this.kundenOrderNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrderDatum
    {
        get
        {
            return this.orderDatumField;
        }
        set
        {
            this.orderDatumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AuftragsDatum
    {
        get
        {
            return this.auftragsDatumField;
        }
        set
        {
            this.auftragsDatumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Saison
    {
        get
        {
            return this.saisonField;
        }
        set
        {
            this.saisonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Auftragstyp
    {
        get
        {
            return this.auftragstypField;
        }
        set
        {
            this.auftragstypField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Auftragsart
    {
        get
        {
            return this.auftragsartField;
        }
        set
        {
            this.auftragsartField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Terminart
    {
        get
        {
            return this.terminartField;
        }
        set
        {
            this.terminartField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LieferDatumAnfang
    {
        get
        {
            return this.lieferDatumAnfangField;
        }
        set
        {
            this.lieferDatumAnfangField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LieferDatumEnde
    {
        get
        {
            return this.lieferDatumEndeField;
        }
        set
        {
            this.lieferDatumEndeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NichtLiefernVor
    {
        get
        {
            return this.nichtLiefernVorField;
        }
        set
        {
            this.nichtLiefernVorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ILNBesteller
    {
        get
        {
            return this.iLNBestellerField;
        }
        set
        {
            this.iLNBestellerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BestName1
    {
        get
        {
            return this.bestName1Field;
        }
        set
        {
            this.bestName1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BestName2
    {
        get
        {
            return this.bestName2Field;
        }
        set
        {
            this.bestName2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BestName3
    {
        get
        {
            return this.bestName3Field;
        }
        set
        {
            this.bestName3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BestStrasse
    {
        get
        {
            return this.bestStrasseField;
        }
        set
        {
            this.bestStrasseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BestLand
    {
        get
        {
            return this.bestLandField;
        }
        set
        {
            this.bestLandField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BestOrt
    {
        get
        {
            return this.bestOrtField;
        }
        set
        {
            this.bestOrtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BestPlz
    {
        get
        {
            return this.bestPlzField;
        }
        set
        {
            this.bestPlzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BesteMail
    {
        get
        {
            return this.besteMailField;
        }
        set
        {
            this.besteMailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BestTelefon
    {
        get
        {
            return this.bestTelefonField;
        }
        set
        {
            this.bestTelefonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BestFax
    {
        get
        {
            return this.bestFaxField;
        }
        set
        {
            this.bestFaxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ILNLiAnschrift
    {
        get
        {
            return this.iLNLiAnschriftField;
        }
        set
        {
            this.iLNLiAnschriftField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefAdressId
    {
        get
        {
            return this.liefAdressIdField;
        }
        set
        {
            this.liefAdressIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefName1
    {
        get
        {
            return this.liefName1Field;
        }
        set
        {
            this.liefName1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefName2
    {
        get
        {
            return this.liefName2Field;
        }
        set
        {
            this.liefName2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefName3
    {
        get
        {
            return this.liefName3Field;
        }
        set
        {
            this.liefName3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefStrasse
    {
        get
        {
            return this.liefStrasseField;
        }
        set
        {
            this.liefStrasseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefLand
    {
        get
        {
            return this.liefLandField;
        }
        set
        {
            this.liefLandField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefOrt
    {
        get
        {
            return this.liefOrtField;
        }
        set
        {
            this.liefOrtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefPlz
    {
        get
        {
            return this.liefPlzField;
        }
        set
        {
            this.liefPlzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefeMail
    {
        get
        {
            return this.liefeMailField;
        }
        set
        {
            this.liefeMailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefTelefon
    {
        get
        {
            return this.liefTelefonField;
        }
        set
        {
            this.liefTelefonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LiefFax
    {
        get
        {
            return this.liefFaxField;
        }
        set
        {
            this.liefFaxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ILNReAnschrift
    {
        get
        {
            return this.iLNReAnschriftField;
        }
        set
        {
            this.iLNReAnschriftField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RechName1
    {
        get
        {
            return this.rechName1Field;
        }
        set
        {
            this.rechName1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RechName2
    {
        get
        {
            return this.rechName2Field;
        }
        set
        {
            this.rechName2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RechName3
    {
        get
        {
            return this.rechName3Field;
        }
        set
        {
            this.rechName3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RechStrasse
    {
        get
        {
            return this.rechStrasseField;
        }
        set
        {
            this.rechStrasseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RechLand
    {
        get
        {
            return this.rechLandField;
        }
        set
        {
            this.rechLandField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RechOrt
    {
        get
        {
            return this.rechOrtField;
        }
        set
        {
            this.rechOrtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RechPlz
    {
        get
        {
            return this.rechPlzField;
        }
        set
        {
            this.rechPlzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecheMail
    {
        get
        {
            return this.recheMailField;
        }
        set
        {
            this.recheMailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RechTelefon
    {
        get
        {
            return this.rechTelefonField;
        }
        set
        {
            this.rechTelefonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RechFax
    {
        get
        {
            return this.rechFaxField;
        }
        set
        {
            this.rechFaxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bestellart
    {
        get
        {
            return this.bestellartField;
        }
        set
        {
            this.bestellartField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Versandart
    {
        get
        {
            return this.versandartField;
        }
        set
        {
            this.versandartField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZahlungsBed
    {
        get
        {
            return this.zahlungsBedField;
        }
        set
        {
            this.zahlungsBedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LieferBed
    {
        get
        {
            return this.lieferBedField;
        }
        set
        {
            this.lieferBedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Waehrung
    {
        get
        {
            return this.waehrungField;
        }
        set
        {
            this.waehrungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bemerkung
    {
        get
        {
            return this.bemerkungField;
        }
        set
        {
            this.bemerkungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MwStStatus
    {
        get
        {
            return this.mwStStatusField;
        }
        set
        {
            this.mwStStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MwSt1Satz
    {
        get
        {
            return this.mwSt1SatzField;
        }
        set
        {
            this.mwSt1SatzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MwSt2Satz
    {
        get
        {
            return this.mwSt2SatzField;
        }
        set
        {
            this.mwSt2SatzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BruttoRechnung
    {
        get
        {
            return this.bruttoRechnungField;
        }
        set
        {
            this.bruttoRechnungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PreislisteNr
    {
        get
        {
            return this.preislisteNrField;
        }
        set
        {
            this.preislisteNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PreislisteProgramm
    {
        get
        {
            return this.preislisteProgrammField;
        }
        set
        {
            this.preislisteProgrammField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Swift
    {
        get
        {
            return this.swiftField;
        }
        set
        {
            this.swiftField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IBAN
    {
        get
        {
            return this.iBANField;
        }
        set
        {
            this.iBANField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SEPAMandattyp
    {
        get
        {
            return this.sEPAMandattypField;
        }
        set
        {
            this.sEPAMandattypField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SEPAMandatnr
    {
        get
        {
            return this.sEPAMandatnrField;
        }
        set
        {
            this.sEPAMandatnrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Sprache
    {
        get
        {
            return this.spracheField;
        }
        set
        {
            this.spracheField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Teillieferung
    {
        get
        {
            return this.teillieferungField;
        }
        set
        {
            this.teillieferungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Valutadatum
    {
        get
        {
            return this.valutadatumField;
        }
        set
        {
            this.valutadatumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Versandkosten
    {
        get
        {
            return this.versandkostenField;
        }
        set
        {
            this.versandkostenField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VersandkostenGebuehr
    {
        get
        {
            return this.versandkostenGebuehrField;
        }
        set
        {
            this.versandkostenGebuehrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VersandkostenText
    {
        get
        {
            return this.versandkostenTextField;
        }
        set
        {
            this.versandkostenTextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VersandkostenMwst
    {
        get
        {
            return this.versandkostenMwstField;
        }
        set
        {
            this.versandkostenMwstField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZANummer
    {
        get
        {
            return this.zANummerField;
        }
        set
        {
            this.zANummerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZABezeichnung
    {
        get
        {
            return this.zABezeichnungField;
        }
        set
        {
            this.zABezeichnungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZAReferenz
    {
        get
        {
            return this.zAReferenzField;
        }
        set
        {
            this.zAReferenzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZAAbschlag
    {
        get
        {
            return this.zAAbschlagField;
        }
        set
        {
            this.zAAbschlagField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZATyp
    {
        get
        {
            return this.zATypField;
        }
        set
        {
            this.zATypField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZAPreis
    {
        get
        {
            return this.zAPreisField;
        }
        set
        {
            this.zAPreisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZABankname
    {
        get
        {
            return this.zABanknameField;
        }
        set
        {
            this.zABanknameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZABLZ
    {
        get
        {
            return this.zABLZField;
        }
        set
        {
            this.zABLZField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZAKontonr
    {
        get
        {
            return this.zAKontonrField;
        }
        set
        {
            this.zAKontonrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZAKontoinhaber
    {
        get
        {
            return this.zAKontoinhaberField;
        }
        set
        {
            this.zAKontoinhaberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZABezahltAm
    {
        get
        {
            return this.zABezahltAmField;
        }
        set
        {
            this.zABezahltAmField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Besteller
    {
        get
        {
            return this.bestellerField;
        }
        set
        {
            this.bestellerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UstID
    {
        get
        {
            return this.ustIDField;
        }
        set
        {
            this.ustIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Skonto1Tage
    {
        get
        {
            return this.skonto1TageField;
        }
        set
        {
            this.skonto1TageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Skonto1Proz
    {
        get
        {
            return this.skonto1ProzField;
        }
        set
        {
            this.skonto1ProzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Skonto2Tage
    {
        get
        {
            return this.skonto2TageField;
        }
        set
        {
            this.skonto2TageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Skonto2Proz
    {
        get
        {
            return this.skonto2ProzField;
        }
        set
        {
            this.skonto2ProzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NettoTage
    {
        get
        {
            return this.nettoTageField;
        }
        set
        {
            this.nettoTageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VertreterNr
    {
        get
        {
            return this.vertreterNrField;
        }
        set
        {
            this.vertreterNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Lagerort
    {
        get
        {
            return this.lagerortField;
        }
        set
        {
            this.lagerortField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LagerOrt-Nach", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LagerOrtNach
    {
        get
        {
            return this.lagerOrtNachField;
        }
        set
        {
            this.lagerOrtNachField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Shopnummer
    {
        get
        {
            return this.shopnummerField;
        }
        set
        {
            this.shopnummerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KopfRabatt1
    {
        get
        {
            return this.kopfRabatt1Field;
        }
        set
        {
            this.kopfRabatt1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KopfRabatt1Id
    {
        get
        {
            return this.kopfRabatt1IdField;
        }
        set
        {
            this.kopfRabatt1IdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KopfRabatt2
    {
        get
        {
            return this.kopfRabatt2Field;
        }
        set
        {
            this.kopfRabatt2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KopfRabatt2Id
    {
        get
        {
            return this.kopfRabatt2IdField;
        }
        set
        {
            this.kopfRabatt2IdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Kollektion
    {
        get
        {
            return this.kollektionField;
        }
        set
        {
            this.kollektionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Produktbereich
    {
        get
        {
            return this.produktbereichField;
        }
        set
        {
            this.produktbereichField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DiverseKundenNr
    {
        get
        {
            return this.diverseKundenNrField;
        }
        set
        {
            this.diverseKundenNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrderIDFremdsystem
    {
        get
        {
            return this.orderIDFremdsystemField;
        }
        set
        {
            this.orderIDFremdsystemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Suchmerkmal
    {
        get
        {
            return this.suchmerkmalField;
        }
        set
        {
            this.suchmerkmalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rechnungstyp
    {
        get
        {
            return this.rechnungstypField;
        }
        set
        {
            this.rechnungstypField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Freitext1
    {
        get
        {
            return this.freitext1Field;
        }
        set
        {
            this.freitext1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZAText1
    {
        get
        {
            return this.zAText1Field;
        }
        set
        {
            this.zAText1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BemerkungIntern
    {
        get
        {
            return this.bemerkungInternField;
        }
        set
        {
            this.bemerkungInternField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Streckenlieferung
    {
        get
        {
            return this.streckenlieferungField;
        }
        set
        {
            this.streckenlieferungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ORDPOS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EDIBODYORDERSORDPOS[] ORDPOS
    {
        get
        {
            return this.oRDPOSField;
        }
        set
        {
            this.oRDPOSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class EDIBODYORDERSORDPOS
{

    private string posFunktionField;

    private string posNummerField;

    private string barcodeField;

    private string artNumFormField;

    private string artNumQualField;

    private string artFarbeField;

    private string artVarianteField;

    private string artAufmachungField;

    private string artGroesseField;

    private string artSetKzField;

    private string posMengeField;

    private string artNumKundeField;

    private string posMwStSchlField;

    private string preisRegField;

    private string preisEffField;

    private string posRabattField;

    private string posRabattIdField;

    private string vonLieferterminField;

    private string bisLieferterminField;

    private string posBemerkungField;

    private string sortimentsKZField;

    private string sortimentsAnzahlField;

    private string themaField;

    private string veField;

    private string schluesselNrField;

    private string gutscheinNrField;

    private string gutscheinSerieField;

    private string rueckgabegrundField;

    private string bestandskzField;

    private string ohneBerechnungField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PosFunktion
    {
        get
        {
            return this.posFunktionField;
        }
        set
        {
            this.posFunktionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PosNummer
    {
        get
        {
            return this.posNummerField;
        }
        set
        {
            this.posNummerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Barcode
    {
        get
        {
            return this.barcodeField;
        }
        set
        {
            this.barcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ArtNumForm
    {
        get
        {
            return this.artNumFormField;
        }
        set
        {
            this.artNumFormField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ArtNumQual
    {
        get
        {
            return this.artNumQualField;
        }
        set
        {
            this.artNumQualField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ArtFarbe
    {
        get
        {
            return this.artFarbeField;
        }
        set
        {
            this.artFarbeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ArtVariante
    {
        get
        {
            return this.artVarianteField;
        }
        set
        {
            this.artVarianteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ArtAufmachung
    {
        get
        {
            return this.artAufmachungField;
        }
        set
        {
            this.artAufmachungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ArtGroesse
    {
        get
        {
            return this.artGroesseField;
        }
        set
        {
            this.artGroesseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ArtSetKz
    {
        get
        {
            return this.artSetKzField;
        }
        set
        {
            this.artSetKzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PosMenge
    {
        get
        {
            return this.posMengeField;
        }
        set
        {
            this.posMengeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ArtNumKunde
    {
        get
        {
            return this.artNumKundeField;
        }
        set
        {
            this.artNumKundeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PosMwStSchl
    {
        get
        {
            return this.posMwStSchlField;
        }
        set
        {
            this.posMwStSchlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PreisReg
    {
        get
        {
            return this.preisRegField;
        }
        set
        {
            this.preisRegField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PreisEff
    {
        get
        {
            return this.preisEffField;
        }
        set
        {
            this.preisEffField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PosRabatt
    {
        get
        {
            return this.posRabattField;
        }
        set
        {
            this.posRabattField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PosRabattId
    {
        get
        {
            return this.posRabattIdField;
        }
        set
        {
            this.posRabattIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VonLiefertermin
    {
        get
        {
            return this.vonLieferterminField;
        }
        set
        {
            this.vonLieferterminField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BisLiefertermin
    {
        get
        {
            return this.bisLieferterminField;
        }
        set
        {
            this.bisLieferterminField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PosBemerkung
    {
        get
        {
            return this.posBemerkungField;
        }
        set
        {
            this.posBemerkungField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SortimentsKZ
    {
        get
        {
            return this.sortimentsKZField;
        }
        set
        {
            this.sortimentsKZField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SortimentsAnzahl
    {
        get
        {
            return this.sortimentsAnzahlField;
        }
        set
        {
            this.sortimentsAnzahlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Thema
    {
        get
        {
            return this.themaField;
        }
        set
        {
            this.themaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VE
    {
        get
        {
            return this.veField;
        }
        set
        {
            this.veField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SchluesselNr
    {
        get
        {
            return this.schluesselNrField;
        }
        set
        {
            this.schluesselNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GutscheinNr
    {
        get
        {
            return this.gutscheinNrField;
        }
        set
        {
            this.gutscheinNrField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GutscheinSerie
    {
        get
        {
            return this.gutscheinSerieField;
        }
        set
        {
            this.gutscheinSerieField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rueckgabegrund
    {
        get
        {
            return this.rueckgabegrundField;
        }
        set
        {
            this.rueckgabegrundField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bestandskz
    {
        get
        {
            return this.bestandskzField;
        }
        set
        {
            this.bestandskzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OhneBerechnung
    {
        get
        {
            return this.ohneBerechnungField;
        }
        set
        {
            this.ohneBerechnungField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class EDIHEADER
{

    private string dOKUMENTTYPField;

    private string dOKUMENTIDField;

    private string dOKUMENTDATUMField;

    private string eMPFAENGERIDField;

    private string aBSENDERIDField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DOKUMENTTYP
    {
        get
        {
            return this.dOKUMENTTYPField;
        }
        set
        {
            this.dOKUMENTTYPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DOKUMENTID
    {
        get
        {
            return this.dOKUMENTIDField;
        }
        set
        {
            this.dOKUMENTIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DOKUMENTDATUM
    {
        get
        {
            return this.dOKUMENTDATUMField;
        }
        set
        {
            this.dOKUMENTDATUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EMPFAENGERID
    {
        get
        {
            return this.eMPFAENGERIDField;
        }
        set
        {
            this.eMPFAENGERIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ABSENDERID
    {
        get
        {
            return this.aBSENDERIDField;
        }
        set
        {
            this.aBSENDERIDField = value;
        }
    }
}
