//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.UserAgents = new HashSet<UserAgents>();
            this.Customer = new HashSet<Customer>();
        }
    
        public string AgentID { get; set; }
        public string AgentNumber { get; set; }
        public string AgentConfirmFax { get; set; }
        public string AgentConfirmEmail { get; set; }
        public string AgentRemark { get; set; }
        public decimal AgentCommission { get; set; }
        public string AgentName1 { get; set; }
        public string AgentName2 { get; set; }
        public string AgentCity { get; set; }
        public string AgentZIP { get; set; }
        public string AgentStreet { get; set; }
        public string AgentPhone { get; set; }
        public string AgentFax { get; set; }
        public string AgentEMail { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string AgentMobile { get; set; }
        public string AgentCountryName { get; set; }
        public string AgentCountryCode { get; set; }
        public string AgentClientID { get; set; }
        public Nullable<bool> IsTestData { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<UserAgents> UserAgents { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
    }
}
