//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Color = new HashSet<Color>();
        }
    
        public string ArticleID { get; set; }
        public string ModelID { get; set; }
        public string ArticleName { get; set; }
        public string ArticleNumber { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string ArticleMaterial { get; set; }
        public string ArticleOrigin { get; set; }
        public string ArticleClientID { get; set; }
        public string ArticleGroupe1 { get; set; }
        public string ArticleGroupe2 { get; set; }
        public string ArticleHeelTypeNumber { get; set; }
        public string ArticleClosingTypeNumber { get; set; }
        public string ArticleClosingType { get; set; }
        public string ArticleTypeNumber { get; set; }
        public string ArticleTypeName { get; set; }
        public string ArticleEASMaterial { get; set; }
        public string ArticleEASMaterialNumber { get; set; }
        public string ArticleEASTypeName { get; set; }
        public string ArticleEASTypeNumber { get; set; }
        public string ArticleHeelTypeName { get; set; }
        public string ArticleCategory1 { get; set; }
        public string ArticleCategory2 { get; set; }
        public string ArticleCategory3 { get; set; }
        public string ArticleImage { get; set; }
        public string ArticleInfoText1 { get; set; }
        public string ArticleInfoText2 { get; set; }
        public string BauerfeindMaterial { get; set; }
        public Nullable<bool> IsTestData { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual ICollection<Color> Color { get; set; }
    }
}
