//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationMember
    {
        public string AssociationMemberID { get; set; }
        public string AssociationMemberNumber { get; set; }
        public string AssociationMemberCustomerID { get; set; }
        public string AssociationMemberAssociationID { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string AssociationMemberClientID { get; set; }
        public Nullable<bool> IsTestData { get; set; }
    }
}
