//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Agent = new HashSet<Agent>();
        }
    
        public string ClientID { get; set; }
        public string ClientName { get; set; }
        public string AccentColor { get; set; }
        public string AccentLowColor { get; set; }
        public string AccentHighColor { get; set; }
        public string Image { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string AccentColorString { get; set; }
        public string ImagePathString { get; set; }
        public string AddressName1 { get; set; }
        public string AddressName2 { get; set; }
        public string AddressStreet { get; set; }
        public string AddressZip { get; set; }
        public string AddressCity { get; set; }
        public string AddressCountryCode { get; set; }
        public string AddressCountryName { get; set; }
        public string Addressline { get; set; }
        public string FooterLeftLine1 { get; set; }
        public string FooterLeftLine2 { get; set; }
        public string FooterLeftLine3 { get; set; }
        public string FooterLeftLine4 { get; set; }
        public string FooterRightLine1 { get; set; }
        public string FooterRightLine2 { get; set; }
        public string FooterRightLine3 { get; set; }
        public string FooterRightLine4 { get; set; }
    
        public virtual ICollection<Agent> Agent { get; set; }
    }
}
