//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color_Compare
    {
        public string ColorID { get; set; }
        public string ColorArticleID { get; set; }
        public string ColorNumber { get; set; }
        public string ColorName { get; set; }
        public bool StockArticle { get; set; }
        public bool ProductionArticle { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DeliveryDateStart { get; set; }
        public System.DateTime DeliveryDateEnd { get; set; }
        public string ColorClientID { get; set; }
        public string EASColorNumber { get; set; }
        public string EASColorName { get; set; }
        public string ColorText1 { get; set; }
        public string ColorImage { get; set; }
        public string CollectionName { get; set; }
        public string ColorNumberText { get; set; }
        public string ColorNumberSearchText { get; set; }
        public string ColorStatus { get; set; }
        public string ColorLiningName { get; set; }
        public string ColorLiningName2 { get; set; }
        public string ColorLiningNumber { get; set; }
        public string ColorLiningNumber2 { get; set; }
        public Nullable<bool> IsTestData { get; set; }
        public string ColorText01 { get; set; }
        public string ColorText02 { get; set; }
        public string ColorText03 { get; set; }
        public string ColorText04 { get; set; }
        public string ColorText05 { get; set; }
        public string ColorText06 { get; set; }
        public string ColorText07 { get; set; }
        public string ColorText08 { get; set; }
        public string ColorText09 { get; set; }
        public string ColorText10 { get; set; }
        public string ColorHeader01 { get; set; }
        public string ColorHeader02 { get; set; }
        public string ColorHeader03 { get; set; }
        public string ColorHeader04 { get; set; }
        public string ColorHeader05 { get; set; }
        public string ColorHeader06 { get; set; }
        public string ColorHeader07 { get; set; }
        public string ColorHeader08 { get; set; }
        public string ColorHeader09 { get; set; }
        public string ColorHeader10 { get; set; }
    }
}
