//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public string ContactPersonID { get; set; }
        public string ContactPersonCustomerID { get; set; }
        public string ContactPersonName1 { get; set; }
        public string ContactPersonName2 { get; set; }
        public string ContactPersonName3 { get; set; }
        public string ContactPersonFunction { get; set; }
        public string ContactPersonEmail { get; set; }
        public string ContactPersonPhone { get; set; }
        public string ContactPersonTitle { get; set; }
        public string ContactPersonClientID { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string ContactPersonFax { get; set; }
        public string ContactPersonNumber { get; set; }
        public Nullable<bool> IsTestData { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
