//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string CountryID { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public string CountryClientID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public Nullable<bool> IsTestData { get; set; }
        public long SyncDateTimeSort { get; set; }
    }
}
