//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.ContactPerson = new HashSet<ContactPerson>();
            this.DeliveryAddress = new HashSet<DeliveryAddress>();
            this.InvoiceAddress = new HashSet<InvoiceAddress>();
        }
    
        public string CustomerID { get; set; }
        public string CustomerName1 { get; set; }
        public string CustomerName2 { get; set; }
        public string CustomerName3 { get; set; }
        public string CustomerStreet { get; set; }
        public string CustomerZIP { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerFax { get; set; }
        public string CustomerPricelistID { get; set; }
        public double CustomerDiscount { get; set; }
        public string CustomerNumber { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public string CustomerTaxID { get; set; }
        public int CustomerValuta { get; set; }
        public string CustomerAgentID { get; set; }
        public bool IsDeleted { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerCountryName { get; set; }
        public string CustomerCountryCode { get; set; }
        public string PaymentTermText { get; set; }
        public string PaymentTermNumber { get; set; }
        public string PricelistName { get; set; }
        public string PricelistNumber { get; set; }
        public string AgentName1 { get; set; }
        public string AgentNumber { get; set; }
        public string AssociationMemberNumber { get; set; }
        public string Customergroup { get; set; }
        public string Currency { get; set; }
        public double lat { get; set; }
        public double lon { get; set; }
        public string CustomerClientID { get; set; }
        public string CustomerBarrier { get; set; }
        public Nullable<bool> IsTestData { get; set; }
        public Nullable<double> OpenReceivables { get; set; }
        public string CustomerText01 { get; set; }
        public string CustomerText02 { get; set; }
        public string CustomerText03 { get; set; }
        public string CustomerText04 { get; set; }
        public string CustomerText05 { get; set; }
        public string CustomerText06 { get; set; }
        public string CustomerText07 { get; set; }
        public string CustomerText08 { get; set; }
        public string CustomerText09 { get; set; }
        public string CustomerHeader01 { get; set; }
        public string CustomerHeader02 { get; set; }
        public string CustomerHeader03 { get; set; }
        public string CustomerHeader04 { get; set; }
        public string CustomerHeader05 { get; set; }
        public string CustomerHeader06 { get; set; }
        public string CustomerHeader07 { get; set; }
        public string CustomerHeader08 { get; set; }
        public string CustomerHeader09 { get; set; }
        public long SyncDateTimeSort { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ICollection<ContactPerson> ContactPerson { get; set; }
        public virtual Pricelist Pricelist { get; set; }
        public virtual ICollection<DeliveryAddress> DeliveryAddress { get; set; }
        public virtual ICollection<InvoiceAddress> InvoiceAddress { get; set; }
    }
}
