//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNote
    {
        public string CustomerNoteID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime Created { get; set; }
        public string Remark { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string CustomerNoteClientID { get; set; }
        public byte[] Image { get; set; }
    }
}
