//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAddress_Compare
    {
        public string DeliveryAddressID { get; set; }
        public string DeliveryAddressCustomerID { get; set; }
        public string DeliveryAddressName1 { get; set; }
        public string DeliveryAddressName2 { get; set; }
        public string DeliveryAddressName3 { get; set; }
        public string DeliveryAddressStreet { get; set; }
        public string DeliveryAddressZIP { get; set; }
        public string DeliveryAddressCity { get; set; }
        public string DeliveryAddressEMail { get; set; }
        public string DeliveryAddressPhone { get; set; }
        public string DeliveryAddressFax { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string DeliveryAddressCountryName { get; set; }
        public string DeliveryAddressCountryCode { get; set; }
        public string DeliveryNumber { get; set; }
        public string DeliveryAddressClientID { get; set; }
        public Nullable<bool> IsTestData { get; set; }
    }
}
