//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAddress
    {
        public string InvoiceAddressID { get; set; }
        public string InvoiceAddressCustomerID { get; set; }
        public string InvoiceAddressName1 { get; set; }
        public string InvoiceAddressName2 { get; set; }
        public string InvoiceAddressName3 { get; set; }
        public string InvoiceAddressStreet { get; set; }
        public string InvoiceAddressZIP { get; set; }
        public string InvoiceAddressCity { get; set; }
        public string InvoiceAddressEMail { get; set; }
        public string InvoiceAddressPhone { get; set; }
        public string InvoiceAddressFax { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string InvoiceAddressCountryName { get; set; }
        public string InvoiceAddressCountryCode { get; set; }
        public string InvoiceAddressClientID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<bool> IsTestData { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
