//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model_Compare
    {
        public string ModelID { get; set; }
        public string ModelName { get; set; }
        public string ModelNumber { get; set; }
        public string ModelSeasonID { get; set; }
        public string ModelImage { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string ModelClientID { get; set; }
        public string FormName { get; set; }
        public string FormNumber { get; set; }
        public string ProductGroup { get; set; }
        public string Width { get; set; }
        public string SoleTypeName { get; set; }
        public Nullable<bool> IsTestData { get; set; }
    }
}
