//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderID { get; set; }
        public string ShoppingCartID { get; set; }
        public string ShoppingCartTitle { get; set; }
        public System.DateTime ShoppingCartCreationDateTime { get; set; }
        public string OrderNumber { get; set; }
        public string OrderTypeID { get; set; }
        public string OrderTypeText { get; set; }
        public string UserID { get; set; }
        public long Sent { get; set; }
        public System.DateTime SentDateTime { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public long SampleOrder { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string ConfirmationEmail { get; set; }
        public string OrderType2 { get; set; }
        public long SampleUnits { get; set; }
        public long ProcessNumber { get; set; }
        public double ExtraDiscount { get; set; }
        public long ShowPrice { get; set; }
        public long TotalPosCount { get; set; }
        public string PricelistID { get; set; }
        public string PricelistName { get; set; }
        public string PricelistNumber { get; set; }
        public string Currency { get; set; }
        public long IsDefault { get; set; }
        public string PricelistClientID { get; set; }
        public string CustomerID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName1 { get; set; }
        public string CustomerName2 { get; set; }
        public string CustomerName3 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerZIP { get; set; }
        public string CustomerStreet { get; set; }
        public string CustomerCountryID { get; set; }
        public string CustomerCountryName { get; set; }
        public string CustomerCountryCode { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerFax { get; set; }
        public string CustomerEMail { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerPricelistID { get; set; }
        public string Customergroup { get; set; }
        public double CustomerDiscount { get; set; }
        public string CustomerTaxID { get; set; }
        public double CustomerComplaintDiscount { get; set; }
        public long CustomerValuta { get; set; }
        public string CustomerAgentID { get; set; }
        public string PaymentTermText { get; set; }
        public string PaymentTermNumber { get; set; }
        public string AgentName1 { get; set; }
        public string AgentNumber { get; set; }
        public string CustomerClientID { get; set; }
        public double lat { get; set; }
        public double lon { get; set; }
        public string CustomerBarrier { get; set; }
        public long IsFavorite { get; set; }
        public string LabelID { get; set; }
        public string LabelName { get; set; }
        public string LabelNumber { get; set; }
        public string LabelClientID { get; set; }
        public string SeasonID { get; set; }
        public string SeasonNumber { get; set; }
        public string SeasonName { get; set; }
        public long SeasonSort { get; set; }
        public string SeasonLabelID { get; set; }
        public string SeasonClientID { get; set; }
        public string DeliveryAddressID { get; set; }
        public string DeliveryAddressCustomerID { get; set; }
        public string DeliveryAddressName1 { get; set; }
        public string DeliveryAddressName2 { get; set; }
        public string DeliveryAddressName3 { get; set; }
        public string DeliveryAddressCity { get; set; }
        public string DeliveryAddressZIP { get; set; }
        public string DeliveryAddressStreet { get; set; }
        public string DeliveryAddressCountryName { get; set; }
        public string DeliveryAddressCountryCode { get; set; }
        public string DeliveryAddressPhone { get; set; }
        public string DeliveryAddressFax { get; set; }
        public string DeliveryAddressEMail { get; set; }
        public string DeliveryAddressMobile { get; set; }
        public string DeliveryAddressClientID { get; set; }
        public string DeliveryAddressCountryID { get; set; }
        public string InvoiceAddressID { get; set; }
        public string InvoiceAddressCustomerID { get; set; }
        public string InvoiceAddressName1 { get; set; }
        public string InvoiceAddressName2 { get; set; }
        public string InvoiceAddressName3 { get; set; }
        public string InvoiceAddressCity { get; set; }
        public string InvoiceAddressZIP { get; set; }
        public string InvoiceAddressStreet { get; set; }
        public string InvoiceAddressCountryName { get; set; }
        public string InvoiceAddressCountryCode { get; set; }
        public string InvoiceAddressPhone { get; set; }
        public string InvoiceAddressFax { get; set; }
        public string InvoiceAddressEMail { get; set; }
        public string InvoiceAddressMobile { get; set; }
        public string InvoiceAddressClientID { get; set; }
        public string InvoiceAddressCountryID { get; set; }
        public string AssociationID { get; set; }
        public string AssociationNumber { get; set; }
        public string AssociationName1 { get; set; }
        public string AssociationName2 { get; set; }
        public string AssociationName3 { get; set; }
        public string AssociationCity { get; set; }
        public string AssociationZIP { get; set; }
        public string AssociationStreet { get; set; }
        public string AssociationCountryName { get; set; }
        public string AssociationCountryCode { get; set; }
        public string AssociationPhone { get; set; }
        public string AssociationFax { get; set; }
        public string AssociationEMail { get; set; }
        public string AssociationMobile { get; set; }
        public string AssociationPricelistID { get; set; }
        public string AssociationClientID { get; set; }
        public string AssociationMemberID { get; set; }
        public string AssociationMemberNumber { get; set; }
        public string AssociationMemberCustomerID { get; set; }
        public string AssociationMemberAssociationID { get; set; }
        public string AssociationMemberClientID { get; set; }
        public long IsDeleted { get; set; }
        public long IsModified { get; set; }
        public System.DateTime SyncDateTime { get; set; }
    }
}
