//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public string OrderItemID { get; set; }
        public string ArticleCategory1 { get; set; }
        public string ArticleCategory2 { get; set; }
        public string ArticleCategory3 { get; set; }
        public string ArticleClientID { get; set; }
        public string ArticleClosingType { get; set; }
        public string ArticleClosingTypeNumber { get; set; }
        public string ArticleCollectionName { get; set; }
        public string ArticleCollectionNumber { get; set; }
        public string ArticleEASMaterial { get; set; }
        public string ArticleEASMaterialNumber { get; set; }
        public string ArticleEASTypeName { get; set; }
        public string ArticleEASTypeNumber { get; set; }
        public string ArticleGroupe1 { get; set; }
        public string ArticleGroupe2 { get; set; }
        public string ArticleHeelTypeName { get; set; }
        public string ArticleHeelTypeNumber { get; set; }
        public string ArticleID { get; set; }
        public string ArticleImage { get; set; }
        public string ArticleInfoText1 { get; set; }
        public string ArticleInfoText2 { get; set; }
        public string ArticleLiningName { get; set; }
        public string ArticleLiningName2 { get; set; }
        public string ArticleLiningNumber { get; set; }
        public string ArticleLiningNumber2 { get; set; }
        public string ArticleMaterial { get; set; }
        public string ArticleName { get; set; }
        public string ArticleNumber { get; set; }
        public string ArticleOrigin { get; set; }
        public string ArticleTypeName { get; set; }
        public string ArticleTypeNumber { get; set; }
        public string AssortmentClientID { get; set; }
        public string AssortmentID { get; set; }
        public string AssortmentName { get; set; }
        public long AssortmentQty { get; set; }
        public string AssortmentSizerunID { get; set; }
        public long AssortmentStockQty { get; set; }
        public string BauerfeindMaterial { get; set; }
        public string ColorArticleID { get; set; }
        public string ColorClientID { get; set; }
        public string ColorID { get; set; }
        public string ColorImage { get; set; }
        public string ColorName { get; set; }
        public string ColorNumber { get; set; }
        public string ColorNumberSearchText { get; set; }
        public string ColorNumberText { get; set; }
        public string ColorStatus { get; set; }
        public string CustomerArticleNumber { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime DeliveryDateEnd { get; set; }
        public System.DateTime DeliveryDateStart { get; set; }
        public string EASColorName { get; set; }
        public string EASColorNumber { get; set; }
        public string FormName { get; set; }
        public string FormNumber { get; set; }
        public long IsDeleted { get; set; }
        public long IsFavorite { get; set; }
        public long IsFreeDisposition { get; set; }
        public long IsModified { get; set; }
        public string ModelClientID { get; set; }
        public string ModelID { get; set; }
        public string ModelImage { get; set; }
        public string ModelName { get; set; }
        public string ModelNumber { get; set; }
        public string ModelSeasonID { get; set; }
        public System.DateTime ModifiedDeliveryDateEnd { get; set; }
        public System.DateTime ModifiedDeliveryDateStart { get; set; }
        public string ProductGroup { get; set; }
        public long ProductionArticle { get; set; }
        public long Qty01 { get; set; }
        public long Qty02 { get; set; }
        public long Qty03 { get; set; }
        public long Qty04 { get; set; }
        public long Qty05 { get; set; }
        public long Qty06 { get; set; }
        public long Qty07 { get; set; }
        public long Qty08 { get; set; }
        public long Qty09 { get; set; }
        public long Qty10 { get; set; }
        public long Qty11 { get; set; }
        public long Qty12 { get; set; }
        public long Qty13 { get; set; }
        public long Qty14 { get; set; }
        public long Qty15 { get; set; }
        public long Qty16 { get; set; }
        public long Qty17 { get; set; }
        public long Qty18 { get; set; }
        public long Qty19 { get; set; }
        public long Qty20 { get; set; }
        public long Qty21 { get; set; }
        public long Qty22 { get; set; }
        public long Qty23 { get; set; }
        public long Qty24 { get; set; }
        public long Qty25 { get; set; }
        public long Qty26 { get; set; }
        public long Qty27 { get; set; }
        public long Qty28 { get; set; }
        public long Qty29 { get; set; }
        public long Qty30 { get; set; }
        public string Remark { get; set; }
        public string Remark2 { get; set; }
        public string SampleSize { get; set; }
        public string ShoppingCartID { get; set; }
        public string ShoppingCartItemClientID { get; set; }
        public double ShoppingCartItemDiscount { get; set; }
        public string ShoppingCartItemID { get; set; }
        public long ShoppingCartItemSort { get; set; }
        public string Size01 { get; set; }
        public string Size02 { get; set; }
        public string Size03 { get; set; }
        public string Size04 { get; set; }
        public string Size05 { get; set; }
        public string Size06 { get; set; }
        public string Size07 { get; set; }
        public string Size08 { get; set; }
        public string Size09 { get; set; }
        public string Size10 { get; set; }
        public string Size11 { get; set; }
        public string Size12 { get; set; }
        public string Size13 { get; set; }
        public string Size14 { get; set; }
        public string Size15 { get; set; }
        public string Size16 { get; set; }
        public string Size17 { get; set; }
        public string Size18 { get; set; }
        public string Size19 { get; set; }
        public string Size20 { get; set; }
        public string Size21 { get; set; }
        public string Size22 { get; set; }
        public string Size23 { get; set; }
        public string Size24 { get; set; }
        public string Size25 { get; set; }
        public string Size26 { get; set; }
        public string Size27 { get; set; }
        public string Size28 { get; set; }
        public string Size29 { get; set; }
        public string Size30 { get; set; }
        public string SizerunArticleID { get; set; }
        public string SizerunClientID { get; set; }
        public string SizerunColorID { get; set; }
        public string SizerunID { get; set; }
        public string SizerunName { get; set; }
        public string SizerunNumber { get; set; }
        public string SizerunPrintColor { get; set; }
        public long StockArticle { get; set; }
        public long StockSum { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public string Width { get; set; }
        public long SyncDateTimeSort { get; set; }
    }
}
