//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricat
    {
        public int ID { get; set; }
        public string ECCIdentNumber { get; set; }
        public string ECCManufacturerNumber { get; set; }
        public string ManufacturerArticleName { get; set; }
        public string CatalogueOrderNumber { get; set; }
        public string EASArticleGroup { get; set; }
        public string EASColour { get; set; }
        public string Size { get; set; }
        public string DistributionUnit { get; set; }
        public string ColourNumberOfManufacturer { get; set; }
        public string ColourDescription { get; set; }
        public string ModelDescriptionOfManufacturer { get; set; }
        public string MaterialDescription { get; set; }
        public string BrandDescription { get; set; }
        public string ModelDescription { get; set; }
        public int MinimumOrderQuantity { get; set; }
        public int QuantityPerShippingUnit { get; set; }
        public string Availability { get; set; }
        public string CountryOfOrigin { get; set; }
        public System.DateTime DeliverableFrom { get; set; }
        public System.DateTime DeliverableUntil { get; set; }
        public string ManufacturerSeason { get; set; }
        public double ListPrice { get; set; }
        public double RecommendedRetailPrice { get; set; }
        public string Image { get; set; }
        public string Currency { get; set; }
    }
}
