//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public string PriceID { get; set; }
        public string PriceArticleID { get; set; }
        public string PriceSizerunID { get; set; }
        public string PricePricelistID { get; set; }
        public decimal BuyingPrice { get; set; }
        public decimal SalesPrice { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string PriceClientID { get; set; }
        public string PriceColorID { get; set; }
        public Nullable<bool> IsTestData { get; set; }
        public long SyncDateTimeSort { get; set; }
    
        public virtual Pricelist Pricelist { get; set; }
        public virtual Sizerun Sizerun { get; set; }
        public virtual Color Color { get; set; }
    }
}
