//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonValue
    {
        public string SeasonValueID { get; set; }
        public string CustomerID { get; set; }
        public string SeasonID { get; set; }
        public int QtyPreOrder { get; set; }
        public int Qty { get; set; }
        public decimal ValuePreOrder { get; set; }
        public decimal Value { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}
