//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public string ShoppingCartID { get; set; }
        public string OrderNumber { get; set; }
        public string OrderTypeID { get; set; }
        public string OrderTypeText { get; set; }
        public string UserID { get; set; }
        public string CustomerID { get; set; }
        public bool Sent { get; set; }
        public System.DateTime SentDateTime { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName1 { get; set; }
        public string CustomerName2 { get; set; }
        public string CustomerName3 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerZIP { get; set; }
        public string CustomerStreet { get; set; }
        public string CustomerCountryID { get; set; }
        public string CustomerCountryName { get; set; }
        public string CustomerCountryCode { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerFax { get; set; }
        public string CustomerEMail { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerPricelistID { get; set; }
        public string Customergroup { get; set; }
        public string CustomerPaymentTerm { get; set; }
        public double CustomerDiscount { get; set; }
        public string CustomerTaxID { get; set; }
        public double CustomerComplaintDiscount { get; set; }
        public int CustomerValuta { get; set; }
        public string CustomerAgentID { get; set; }
        public string PaymentTermText { get; set; }
        public string PaymentTermNumber { get; set; }
        public string PricelistName { get; set; }
        public string PricelistNumber { get; set; }
        public string AgentName1 { get; set; }
        public string AgentNumber { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public string LabelID { get; set; }
        public string LabelName { get; set; }
        public string LabelNumber { get; set; }
        public string SeasonID { get; set; }
        public string SeasonNumber { get; set; }
        public string SeasonName { get; set; }
        public int SeasonSort { get; set; }
        public string SeasonLabelID { get; set; }
        public string DeliveryAddressID { get; set; }
        public string DeliveryNumber { get; set; }
        public string DeliveryAddressCustomerID { get; set; }
        public string DeliveryAddressName1 { get; set; }
        public string DeliveryAddressName2 { get; set; }
        public string DeliveryAddressName3 { get; set; }
        public string DeliveryAddressCity { get; set; }
        public string DeliveryAddressZIP { get; set; }
        public string DeliveryAddressStreet { get; set; }
        public string DeliveryAddressCountryName { get; set; }
        public string DeliveryAddressCountryCode { get; set; }
        public string DeliveryAddressPhone { get; set; }
        public string DeliveryAddressFax { get; set; }
        public string DeliveryAddressEMail { get; set; }
        public string DeliveryAddressMobile { get; set; }
        public string InvoiceAddressID { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceAddressCustomerID { get; set; }
        public string InvoiceAddressName1 { get; set; }
        public string InvoiceAddressName2 { get; set; }
        public string InvoiceAddressName3 { get; set; }
        public string InvoiceAddressCity { get; set; }
        public string InvoiceAddressZIP { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public bool SampleOrder { get; set; }
        public string Currency { get; set; }
        public string OrderType2 { get; set; }
        public string AssociationMemberNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool IsModified { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string ConfirmationEmail { get; set; }
        public bool SampleUnits { get; set; }
        public long ProcessNumber { get; set; }
        public int ConfirmationStatus { get; set; }
        public double ExtraDiscount { get; set; }
        public bool ShowPrice { get; set; }
        public string ShoppingCartClientID { get; set; }
        public string DeviceID { get; set; }
        public string DeviceModel { get; set; }
        public string DeviceManufracturer { get; set; }
        public string DeviceName { get; set; }
        public string DeviceOSName { get; set; }
        public string InvoiceAddressCountryName { get; set; }
        public string InvoiceAddressCountryCode { get; set; }
        public string InvoiceAddressPhone { get; set; }
        public string InvoiceAddressFax { get; set; }
        public string InvoiceAddressEMail { get; set; }
        public string InvoiceAddressMobile { get; set; }
        public string CustomerClientID { get; set; }
        public string LabelClientID { get; set; }
        public string SeasonClientID { get; set; }
        public string DeliveryAddressClientID { get; set; }
        public string InvoiceAddressClientID { get; set; }
        public string ShoppingCartTitle { get; set; }
        public string PricelistID { get; set; }
        public bool IsDefault { get; set; }
        public string PricelistClientID { get; set; }
        public bool IsFavorite { get; set; }
        public string DeliveryAddressCountryID { get; set; }
        public string InvoiceAddressCountryID { get; set; }
        public string AssociationID { get; set; }
        public string AssociationNumber { get; set; }
        public string AssociationName1 { get; set; }
        public string AssociationName2 { get; set; }
        public string AssociationName3 { get; set; }
        public string AssociationCity { get; set; }
        public string AssociationZIP { get; set; }
        public string AssociationStreet { get; set; }
        public string AssociationCountryName { get; set; }
        public string AssociationCountryCode { get; set; }
        public string AssociationPhone { get; set; }
        public string AssociationFax { get; set; }
        public string AssociationEMail { get; set; }
        public string AssociationMobile { get; set; }
        public string AssociationPricelistID { get; set; }
        public string AssociationClientID { get; set; }
        public string AssociationMemberID { get; set; }
        public string AssociationMemberCustomerID { get; set; }
        public string AssociationMemberAssociationID { get; set; }
        public string AssociationMemberClientID { get; set; }
        public int StatusID { get; set; }
        public Nullable<bool> IsTestData { get; set; }
        public string TextSnippets { get; set; }
        public Nullable<double> EarlyBirdDiscount { get; set; }
        public Nullable<double> PreorderDiscount { get; set; }
        public Nullable<double> ShoppingCartComplaintDiscount { get; set; }
        public Nullable<double> ShoppingCartCustomerDiscount { get; set; }
        public Nullable<double> CollectionDiscount { get; set; }
        public Nullable<double> ShoppingCartCollectionDiscount { get; set; }
        public Nullable<double> ShoppingCartEarlyBirdDiscount { get; set; }
        public Nullable<double> ShoppingCartPreorderDiscount { get; set; }
        public string InvoiceAddressStreet { get; set; }
        public Nullable<double> ShoppingCartQuantityDiscount { get; set; }
        public Nullable<double> QuantityDiscount { get; set; }
        public string CustomerText01 { get; set; }
        public string CustomerText02 { get; set; }
        public string CustomerText03 { get; set; }
        public string CustomerText04 { get; set; }
        public string CustomerText05 { get; set; }
        public string CustomerText06 { get; set; }
        public string CustomerText07 { get; set; }
        public string CustomerText08 { get; set; }
        public string CustomerText09 { get; set; }
        public string CustomerText10 { get; set; }
        public string CustomerHeader01 { get; set; }
        public string CustomerHeader02 { get; set; }
        public string CustomerHeader03 { get; set; }
        public string CustomerHeader04 { get; set; }
        public string CustomerHeader05 { get; set; }
        public string CustomerHeader06 { get; set; }
        public string CustomerHeader07 { get; set; }
        public string CustomerHeader08 { get; set; }
        public string CustomerHeader09 { get; set; }
        public string CustomerHeader10 { get; set; }
        public string SeasonLongName { get; set; }
        public string AppVersion { get; set; }
        public long SyncDateTimeSort { get; set; }
    }
}
