//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sizerun
    {
        public Sizerun()
        {
            this.Price = new HashSet<Price>();
        }
    
        public string SizerunID { get; set; }
        public string SizerunName { get; set; }
        public string SizerunNumber { get; set; }
        public string Size01 { get; set; }
        public string Size02 { get; set; }
        public string Size03 { get; set; }
        public string Size04 { get; set; }
        public string Size05 { get; set; }
        public string Size06 { get; set; }
        public string Size07 { get; set; }
        public string Size08 { get; set; }
        public string Size09 { get; set; }
        public string Size10 { get; set; }
        public string Size11 { get; set; }
        public string Size12 { get; set; }
        public string Size13 { get; set; }
        public string Size14 { get; set; }
        public string Size15 { get; set; }
        public string Size16 { get; set; }
        public string Size17 { get; set; }
        public string Size18 { get; set; }
        public string Size19 { get; set; }
        public string Size20 { get; set; }
        public string Size21 { get; set; }
        public string Size22 { get; set; }
        public string Size23 { get; set; }
        public string Size24 { get; set; }
        public string Size25 { get; set; }
        public string Size26 { get; set; }
        public string Size27 { get; set; }
        public string Size28 { get; set; }
        public string Size29 { get; set; }
        public string Size30 { get; set; }
        public string PrintColor { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string SizerunClientID { get; set; }
        public string SizerunArticleID { get; set; }
        public string SizerunModelID { get; set; }
        public string SizerunColorID { get; set; }
        public Nullable<bool> IsTestData { get; set; }
        public string EAN01 { get; set; }
        public string EAN02 { get; set; }
        public string EAN03 { get; set; }
        public string EAN04 { get; set; }
        public string EAN05 { get; set; }
        public string EAN06 { get; set; }
        public string EAN07 { get; set; }
        public string EAN08 { get; set; }
        public string EAN09 { get; set; }
        public string EAN10 { get; set; }
        public string EAN11 { get; set; }
        public string EAN12 { get; set; }
        public string EAN13 { get; set; }
        public string EAN14 { get; set; }
        public string EAN15 { get; set; }
        public string EAN16 { get; set; }
        public string EAN17 { get; set; }
        public string EAN18 { get; set; }
        public string EAN19 { get; set; }
        public string EAN20 { get; set; }
        public string EAN21 { get; set; }
        public string EAN22 { get; set; }
        public string EAN23 { get; set; }
        public string EAN24 { get; set; }
        public string EAN25 { get; set; }
        public string EAN26 { get; set; }
        public string EAN27 { get; set; }
        public string EAN28 { get; set; }
        public string EAN29 { get; set; }
        public string EAN30 { get; set; }
    
        public virtual ICollection<Price> Price { get; set; }
    }
}
