//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_Vertreter
    {
        public int Id { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Strasse { get; set; }
        public string Land { get; set; }
        public string Plz { get; set; }
        public string Ort { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Mobil { get; set; }
        public string Email { get; set; }
        public string Kundennr { get; set; }
        public string UID { get; set; }
        public string Steuernr { get; set; }
        public string VertreterNr { get; set; }
    }
}
