//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_Preis
    {
        public int Id { get; set; }
        public string Preislistenr { get; set; }
        public string Saison { get; set; }
        public string Waehrung { get; set; }
        public string EAN { get; set; }
        public decimal HEK { get; set; }
        public decimal EmpfVK { get; set; }
        public string Groesse { get; set; }
        public string ArtikelnrFarbnr { get; set; }
    }
}
