//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_Kunde
    {
        public int Id { get; set; }
        public string Kundennr { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Strasse { get; set; }
        public string Plz { get; set; }
        public string Ort { get; set; }
        public string Land { get; set; }
        public string Zahlungsbed { get; set; }
        public string Zahlungsart { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string homepage { get; set; }
        public string Bonitaetsstufe { get; set; }
        public string Kundentyp { get; set; }
        public string Vertrerternr { get; set; }
        public string UID_Nummer { get; set; }
        public string Preislistennr { get; set; }
        public string Mwst_KZ { get; set; }
        public string Steuerschluessel { get; set; }
        public string Rechnungsempfaenger { get; set; }
        public string Bonitaet { get; set; }
        public string EKV { get; set; }
        public string EKV_KTO { get; set; }
        public Nullable<double> Forderungen { get; set; }
    }
}
