//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_Rabatt
    {
        public int Id { get; set; }
        public string Kundennr { get; set; }
        public string Match { get; set; }
        public string Rabattart { get; set; }
        public double Wert { get; set; }
        public string Berechenart { get; set; }
        public string Wertstellung { get; set; }
        public string Ebene { get; set; }
    }
}
