//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_Lieferadresse
    {
        public int Id { get; set; }
        public string Kundennr { get; set; }
        public string Lieferort { get; set; }
        public string Matchcode { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Strasse { get; set; }
        public string Plz { get; set; }
        public string Ort { get; set; }
        public string Land { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Bemerkung { get; set; }
        public string ILN { get; set; }
        public string Filiale { get; set; }
        public string Bundesstaat { get; set; }
        public string Sendungsenpfaenger { get; set; }
        public string Abladestelle { get; set; }
        public string UKAdresse { get; set; }
        public string Warenempfaengernr { get; set; }
    }
}
