//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_Artikelbeschreibung
    {
        public int Id { get; set; }
        public string Artikelnr { get; set; }
        public string Artikelsaison { get; set; }
        public string Artikelbeschreibung { get; set; }
    }
}
