//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_Saisonumsatz
    {
        public int Id { get; set; }
        public string Saison { get; set; }
        public string Kundennr { get; set; }
        public int MengeVO { get; set; }
        public decimal UmsatzVO { get; set; }
        public int MengeGesamt { get; set; }
        public decimal UmsatzGesamt { get; set; }
    }
}
