//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_Stock
    {
        public int Id { get; set; }
        public string Lagernr { get; set; }
        public string EAN { get; set; }
        public int Freilagerbestand { get; set; }
        public string Artikelsaison { get; set; }
        public Nullable<int> FreiVerfuegbarerBestand { get; set; }
    }
}
