//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_Ansprechpartner
    {
        public int Id { get; set; }
        public string Kundennr { get; set; }
        public string ASP_Nr { get; set; }
        public string ASP_Bereich { get; set; }
        public string ASP_Vorname { get; set; }
        public string ASP_Name1 { get; set; }
        public string ASP_Name2 { get; set; }
        public string ASP_Telefon { get; set; }
        public string ASP_Mobiltelefon { get; set; }
        public string ASP_Fax { get; set; }
        public string ASP_Bemerkung { get; set; }
        public string ASP_Email { get; set; }
    }
}
