//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_Artikel
    {
        public int Id { get; set; }
        public string Artikelnr { get; set; }
        public string Farbnr { get; set; }
        public string Matchcode { get; set; }
        public string Artikelbez1 { get; set; }
        public string Artikelbez2 { get; set; }
        public string Farbe { get; set; }
        public string Groesse { get; set; }
        public string EAN { get; set; }
        public string Produktbereich { get; set; }
        public string Produktgruppe { get; set; }
        public string Kollektion { get; set; }
        public string Artikelsaison { get; set; }
        public string Groessenskala { get; set; }
        public string lieferbareGrVon { get; set; }
        public string lieferbareGrBis { get; set; }
        public string Gewicht { get; set; }
    }
}
