//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_TempSizerun
    {
        public string ID { get; set; }
        public string Size01 { get; set; }
        public string Size02 { get; set; }
        public string Size03 { get; set; }
        public string Size04 { get; set; }
        public string Size05 { get; set; }
        public string Size06 { get; set; }
        public string Size07 { get; set; }
        public string Size08 { get; set; }
        public string Size09 { get; set; }
        public string Size10 { get; set; }
        public string Size11 { get; set; }
        public string Size12 { get; set; }
        public string Size13 { get; set; }
        public string Size14 { get; set; }
        public string Size15 { get; set; }
        public string Size16 { get; set; }
        public string Size17 { get; set; }
        public string Size18 { get; set; }
        public string Size19 { get; set; }
        public string Size20 { get; set; }
        public string Size21 { get; set; }
        public string Size22 { get; set; }
        public string Size23 { get; set; }
        public string Size24 { get; set; }
        public string Size25 { get; set; }
        public string Size26 { get; set; }
        public string Size27 { get; set; }
        public string Size28 { get; set; }
        public string Size29 { get; set; }
        public string Size30 { get; set; }
        public string ColorID { get; set; }
        public string Skala { get; set; }
    }
}
