//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudDataService.TestResource", typeof(TestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ShoppingCart&quot;:{&quot;UploadID&quot;:43,&quot;ShoppingCartID&quot;:&quot;e6a26d7a-6ae2-4d18-a036-f207b30d5377&quot;,&quot;OrderNumber&quot;:&quot;7020129932&quot;,&quot;OrderTypeID&quot;:&quot;0&quot;,&quot;OrderTypeText&quot;:&quot;Terminauftrag&quot;,&quot;UserID&quot;:&quot;lkb_d.maeffert@outlook.com&quot;,&quot;Sent&quot;:false,&quot;SentDateTime&quot;:&quot;1950-01-01T00:00:00&quot;,&quot;CustomerID&quot;:&quot;&quot;,&quot;CustomerNumber&quot;:&quot;-1&quot;,&quot;CustomerName1&quot;:&quot;Frau Bausch&quot;,&quot;CustomerName2&quot;:&quot;Schuh Hug&quot;,&quot;CustomerName3&quot;:&quot;&quot;,&quot;CustomerCity&quot;:&quot;Hinterzarten&quot;,&quot;CustomerZIP&quot;:&quot;79856&quot;,&quot;CustomerStreet&quot;:&quot;Freiburger Str. 21&quot;,&quot;CustomerCountryID&quot;:&quot;0&quot;,&quot;CustomerCountryName&quot;:&quot;Deutschl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UploadContent {
            get {
                return ResourceManager.GetString("UploadContent", resourceCulture);
            }
        }
    }
}
