//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDataService.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfirmResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfirmResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudDataService.res.ConfirmResource", typeof(ConfirmResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertreter.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel Nr..
        /// </summary>
        internal static string ArticleNo {
            get {
                return ResourceManager.GetString("ArticleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einkaufsvereinigung.
        /// </summary>
        internal static string Association {
            get {
                return ResourceManager.GetString("Association", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV-Nummer.
        /// </summary>
        internal static string AssoMemberNumber {
            get {
                return ResourceManager.GetString("AssoMemberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EK.
        /// </summary>
        internal static string BP {
            get {
                return ResourceManager.GetString("BP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kollektionsrabatt.
        /// </summary>
        internal static string CollectionDiscount {
            get {
                return ResourceManager.GetString("CollectionDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbe.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansprechpartner.
        /// </summary>
        internal static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenartikel.
        /// </summary>
        internal static string CustomerArticle {
            get {
                return ResourceManager.GetString("CustomerArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grundrabatt.
        /// </summary>
        internal static string CustomerDiscount {
            get {
                return ResourceManager.GetString("CustomerDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundennummer.
        /// </summary>
        internal static string CustomerNumber {
            get {
                return ResourceManager.GetString("CustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferung an.
        /// </summary>
        internal static string DeliveryTo {
            get {
                return ResourceManager.GetString("DeliveryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wunschtermin.
        /// </summary>
        internal static string DesiredDeliveryDate {
            get {
                return ResourceManager.GetString("DesiredDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabatt.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Früheinteilerrabatt.
        /// </summary>
        internal static string EarlyBirdDiscount {
            get {
                return ResourceManager.GetString("EarlyBirdDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR.
        /// </summary>
        internal static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kostl..
        /// </summary>
        internal static string FoC {
            get {
                return ResourceManager.GetString("FoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung an.
        /// </summary>
        internal static string InvoiceTo {
            get {
                return ResourceManager.GetString("InvoiceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrageingangsbestätigung.
        /// </summary>
        internal static string OrderProposal {
            get {
                return ResourceManager.GetString("OrderProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellformular.
        /// </summary>
        internal static string OrderProposalForm {
            get {
                return ResourceManager.GetString("OrderProposalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellübersicht.
        /// </summary>
        internal static string OrderProposalPreview {
            get {
                return ResourceManager.GetString("OrderProposalPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftragsart.
        /// </summary>
        internal static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftragswert.
        /// </summary>
        internal static string OrderValue {
            get {
                return ResourceManager.GetString("OrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seite {0} von {1}.
        /// </summary>
        internal static string PageXofX {
            get {
                return ResourceManager.GetString("PageXofX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsbedingungen.
        /// </summary>
        internal static string PaymentTerms {
            get {
                return ResourceManager.GetString("PaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vorl. Auftragsnummer.
        /// </summary>
        internal static string PreliminaryOrderNo {
            get {
                return ResourceManager.GetString("PreliminaryOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vororderrabatt.
        /// </summary>
        internal static string PreOrderDiscount {
            get {
                return ResourceManager.GetString("PreOrderDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mengenrabatt.
        /// </summary>
        internal static string QuantityDiscount {
            get {
                return ResourceManager.GetString("QuantityDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkung.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVP.
        /// </summary>
        internal static string RRP {
            get {
                return ResourceManager.GetString("RRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saison.
        /// </summary>
        internal static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setze Liefertermin nicht vor.
        /// </summary>
        internal static string SetDeliveryNotBefore {
            get {
                return ResourceManager.GetString("SetDeliveryNotBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Größengang.
        /// </summary>
        internal static string SizeRange {
            get {
                return ResourceManager.GetString("SizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielen Dank für Ihren Auftrag..
        /// </summary>
        internal static string ThankYouForYourOrder {
            get {
                return ResourceManager.GetString("ThankYouForYourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ges.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt Menge.
        /// </summary>
        internal static string TotalQuantity {
            get {
                return ResourceManager.GetString("TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt Summe.
        /// </summary>
        internal static string TotalValue {
            get {
                return ResourceManager.GetString("TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade ....
        /// </summary>
        internal static string UpdateData {
            get {
                return ResourceManager.GetString("UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates verfügbar.
        /// </summary>
        internal static string UpdatesAvailable {
            get {
                return ResourceManager.GetString("UpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weite.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Auftrags Nr..
        /// </summary>
        internal static string YourOrderNumber {
            get {
                return ResourceManager.GetString("YourOrderNumber", resourceCulture);
            }
        }
    }
}
