//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALESCenterLivingKB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServerEntities : DbContext
    {
        public ServerEntities()
            : base("name=ServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Association> Association { get; set; }
        public virtual DbSet<AssociationMember> AssociationMember { get; set; }
        public virtual DbSet<Assortment> Assortment { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<ContactPerson> ContactPerson { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<DeliveryAddress> DeliveryAddress { get; set; }
        public virtual DbSet<InvoiceAddress> InvoiceAddress { get; set; }
        public virtual DbSet<Label> Label { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Pricelist> Pricelist { get; set; }
        public virtual DbSet<Season> Season { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<ShoppingCartItem> ShoppingCartItem { get; set; }
        public virtual DbSet<Sizerun> Sizerun { get; set; }
        public virtual DbSet<SpecialDiscount> SpecialDiscount { get; set; }
        public virtual DbSet<TextSnippet> TextSnippet { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserAgents> UserAgents { get; set; }
        public virtual DbSet<UserClient> UserClient { get; set; }
        public virtual DbSet<UserPriceList> UserPriceList { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
    }
}
