//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALESCenterLivingKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string StockID { get; set; }
        public string StockAssortmentID { get; set; }
        public int StockQty01 { get; set; }
        public int StockQty02 { get; set; }
        public int StockQty03 { get; set; }
        public int StockQty04 { get; set; }
        public int StockQty05 { get; set; }
        public int StockQty06 { get; set; }
        public int StockQty07 { get; set; }
        public int StockQty08 { get; set; }
        public int StockQty09 { get; set; }
        public int StockQty10 { get; set; }
        public int StockQty11 { get; set; }
        public int StockQty12 { get; set; }
        public int StockQty13 { get; set; }
        public int StockQty14 { get; set; }
        public int StockQty15 { get; set; }
        public int StockQty16 { get; set; }
        public int StockQty17 { get; set; }
        public int StockQty18 { get; set; }
        public int StockQty19 { get; set; }
        public int StockQty20 { get; set; }
        public int StockQty21 { get; set; }
        public int StockQty22 { get; set; }
        public int StockQty23 { get; set; }
        public int StockQty24 { get; set; }
        public int StockQty25 { get; set; }
        public int StockQty26 { get; set; }
        public int StockQty27 { get; set; }
        public int StockQty28 { get; set; }
        public int StockQty29 { get; set; }
        public int StockQty30 { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string StockClientID { get; set; }
        public bool IsFreeDisposition { get; set; }
        public int StockQtyAssortment { get; set; }
        public Nullable<bool> IsTestData { get; set; }
    }
}
