//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALESCenterLivingKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserAgents = new HashSet<UserAgents>();
            this.UserPriceList = new HashSet<UserPriceList>();
        }
    
        public string UserID { get; set; }
        public string UserNumber { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Street { get; set; }
        public string ZIP { get; set; }
        public string City { get; set; }
        public int CountryID { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Internet { get; set; }
        public string Email { get; set; }
        public string ConfirmEmail { get; set; }
        public string PrintColor { get; set; }
        public bool CanEditPrice { get; set; }
        public bool FairMode { get; set; }
        public double MaxCustomerDiscount { get; set; }
        public double MaxComplaintDiscount { get; set; }
        public bool CommisionDecline { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> NextOrderNumber { get; set; }
        public string Agent1 { get; set; }
        public string Agent2 { get; set; }
        public string Agent3 { get; set; }
        public string Agent4 { get; set; }
        public string DefaultPricelist { get; set; }
        public string UserClientID { get; set; }
        public Nullable<bool> UseTestData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAgents> UserAgents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPriceList> UserPriceList { get; set; }
    }
}
