//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALESCenterLivingKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClient
    {
        public string UserMandantID { get; set; }
        public string UserID { get; set; }
        public string UserClientClientID { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}
