//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALESCenterLivingKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPriceList
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string PricelistID { get; set; }
        public Nullable<System.DateTime> SyncDateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UserPricelistClientID { get; set; }
    
        public virtual Pricelist Pricelist { get; set; }
        public virtual User User { get; set; }
    }
}
